#ifndef HtmlContent_h
    #define HtmlContent_h

    #include <WString.h>
    #include <pgmspace.h>

    const char PROGMEM MAIN_PAGE[] = {
        "<html lang=\"en\">"
            "<head>"
                "<title>Lumen Lighting Controller</title>"
                "<style>"
                    "body { background-color: #000000; color: #FFFFFF; }"
                    "h1 { text-align: center; background-color: #5878B0; color: #FFFFFF; border: 3px; }"
                    "h2 { text-align: center; background-color: #58ADB0; color: #FFFFFF; border: 3px;  border-radius: 15px; }"
                    "#wrapper { background-color: #E6EFFF; color: #000000; padding: 20px; margin-left: auto; margin-right: auto; max-width: 700px; box-shadow: 3px 3px 3px #b8b8b8; }"
                    "#info, input { font-size: 25px; font-weight: bold; line-height: 150%; } "
                    "strong { font-size: 30px; }"
                    ".hlt { background-color: #FFFFFF; display: inline; }"
                    ".tiny { font-size: 8px; }"
                    "button { background-color: #5878B0; color: white; font-size: 16px; padding: 10px 24px; border-radius: 12px; border: 2px solid black; transition-duration: 0.4s; }"
                    "button:hover { background-color: white; color: black; }"
                "</style>"
            "</head>"
            "<body>"
                "<div id=\"wrapper\">"
                    "<h1>Lumen Lighting Controller</h1>"
                    "${status_message}"
                    "<div id=\"info\">"
                        "<strong>Light Status:</strong> <div class=\"hlt\">${on_off_status}</div>"
                        "<br />"
                        "<strong>Current Time:</strong> <div class=\"hlt\">${cur_time}</div>"
                        "<br /><br />"
                        "<form action=\"/\" method=\"post\">"
                            "<h2>Timer Control</h2>"
                            "<strong>Status:</strong> <div class=\"hlt\">${timer_on_off}</div>"
                            "<br /><br />"
                            "<button type=\"submit\" name=\"do\" value=\"toggle_timer_state\" ${toggle_hidden}>Toggle</button>"
                            "<br />"
                            "<div ${schedule_hide}>"
                                "<br />"
                                "<strong>Schedule:</strong><br />"
                                "On at: <input type=\"time\" id=\"onat\" name=\"onat\" value=\"${on_at}\" required /><br /s>"
                                "Off at: <input type=\"time\" id=\"offat\" name=\"offat\" value=\"${off_at}\" required />"
                                "<br /><br />"
                                "<button type=\"submit\" name=\"do\" value=\"btn_update\">Update</button>"
                                "<br />"
                            "</div>"
                            "<h2>Manual Controls</h2>"
                            "<table style=\"width: 100%;\">"
                                "<tr>"
                                    "<td align=\"center\"><button type=\"submit\" name=\"do\" value=\"btn_on\">On</button></td>"
                                    "<td align=\"center\"><button type=\"submit\" name=\"do\" value=\"btn_off\">Off</button></td>"
                                "</tr>"
                            "</table>"
                            "<br />"
                            "<hr />"
                            "<br />"
                            "<button type=\"submit\" name=\"do\" value=\"goto_admin\">Settings</button>"
                        "</form>"
                    "</div>"
                    "<div class=\"tiny\">"
                        "<br /><hr /><br />"
                        "About Device:<br />"
                        "SSID: ${ssid}; WiFi Address: ${wifi_addr}<br />"
                        "Firmware Version: ${version}; By: Scott Griffis"
                    "</div>"
                "</div>"
            "</body>"
        "</html>"
    };

    // const char PROGMEM SENSOR_OPTION[] = {
    //     "<option value=\"${id}\" ${selection_flag}>${description}</option>"
    // };

    const char PROGMEM STATUS_MESSAGE[] = {
        "<script>alert(\"${message}\");</script>"
    };

    /**
     * This is the HTML content of the Admin/Settings Page.
     * This HTML has replaceable place-holders for dynamic informaton to be
     * added just prior to sending to client.
    */
    const char PROGMEM SETTINGS_PAGE[] = {
        "<!DOCTYPE HTML>"
        "<html lang=\"en\">"
            "<head>"
                "<title>Lumen Lighting Controller</title>"
                "<style>"
                    "body { background-color: #000000; color: #FFFFFF; }"
                    "h1 { text-align: center; background-color: #5878B0; color: #FFFFFF; border: 3px; }"
                    "h2 { text-align: center; background-color: #58ADB0; color: #FFFFFF; border: 3px;  border-radius: 15px; }"
                    "#wrapper { background-color: #E6EFFF; color: #000000; padding: 20px; margin-left: auto; margin-right: auto; max-width: 700px; box-shadow: 3px 3px 3px #b8b8b8; }"
                    "#info, input { font-size: 25px; font-weight: bold; line-height: 150%; }"
                    "strong { font-size: 30px; }"
                    ".hlt { background-color: #FFFFFF; display: inline; }"
                    ".tiny { font-size: 8px; }"
                    "button { background-color: #5878B0; color: white; font-size: 16px; padding: 10px 24px; border-radius: 12px; border: 2px solid black; transition-duration: 0.4s; }"
                    "button:hover { background-color: white; color: black; }"
                "</style>"
            "</head>"
            "<body>"
                "<div id=\"wrapper\">"
                    "<h1>Settings</h1>"
                    "Firmware Version: ${version}"
                    "<div id=\"info\">"
                        "<form method=\"post\" action=\"/\">"
                            "<h2>Access Point</h2>"
                            "<strong>Password:</strong> <input maxlength=\"50\" type=\"text\" value=\"${ap_pwd}\" name=\"appwd\" id=\"appwd\">"
                            "<h2>WiFi</h2>"
                            "<div>Note: Leave these settings at 'SET_ME' to keep device in AP Mode.</div>"
                            "<br /><br />"
                            "<strong>SSID:</strong> <input maxlength=\"32\" type=\"text\" value=\"${ssid}\" name=\"ssid\" id=\"ssid\"><br />"
                            "<strong>Password:</strong> <input maxlength=\"63\" type=\"text\" value=\"${pwd}\" name=\"pwd\" id=\"pwd\">"
                            "<h2>Admin</h2>"
                            "<strong>Admin User:</strong> <input maxlength=\"50\" type=\"text\" value=\"${adminuser}\" name=\"adminuser\" id=\"adminuser\"><br />"
                            "<strong>Admin Password:</strong> <input maxlength=\"50\" type=\"text\" value=\"${adminpwd}\" name=\"adminpwd\" id=\"adminpwd\"><br />"
                            "<br />"
                            "<button type=\"submit\" name=\"do\" value=\"admin_save\">Save</button>&nbsp;&nbsp;&nbsp;&nbsp;<button type=\"submit\" name=\"do\" value=\"admin_exit\">Exit</button>"
                        "</form>"
                    "</div>"
            "</div>"
            "</body>"
        "</html>"
    };
    
#endif